name: learn-github-actions
#run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
  # can be manual triggered in Actions panel
  workflow_dispatch:
env:
  continue: true
  # Expression
  CUR_BRANCH: ${{ github.ref == 'refs/heads/main' && 'value_for_main_branch' || 'value_for_other_branches' }}
  RUNS_ON: ubuntu-latest
  WORKING-DIRECTORY: "./scripts"
jobs:
  run-scripts-and-shell-commands:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING-DIRECTORY }} # a default working directory for run commands
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # run scripts and shell commands
      - name: Run a script (not executable) without interpreter
        run: "./my-script.sh" # './scripts' => './scripts/my-script.sh'
        continue-on-error: ${{ fromJSON(env.continue) }} # fromJSON() function to convert the environment variable continue from a string to a boolean

      - name: Run a script with interpreter
        run: bash './my-script.sh' # './scripts' => './scripts/my-script.sh'
        # using variables
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

      - name: Make the script files executable
        run: chmod +x my-script.sh
      - name: Run the script
        run: "./my-script.sh" # './scripts' => './scripts/my-script.sh'

      - name: Expressions
        run: echo $CUR_BRANCH

  build-lib:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING-DIRECTORY }} # a default working directory for run commands
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Build
        run: node 'build.js'
      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: dist/

  publish-to-npm:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ${{ env.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: publish
        run: npm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  download-artifacts-from-last-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: run-scripts-and-shell-commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: output-files
      # - run: ls -al
      - name: run the artifact(js)
        run: node lib.js
